#!/bin/bash
while true; do	
	LOCALTIME=$(date | awk {'print $1 " " $2 " " $3 " " substr($4, 1, length($4)-3)'})
        DISKTOTAL=$(df -Ph | grep "/dev/mapper/cryptroot" | awk {'print $2'})
        DISKUSEDP=$(df -Ph | grep "/dev/mapper/cryptroot" | awk {'print $5'})
	DISKUSED=$(df -Ph | grep "/dev/mapper/cryptroot" | awk {'print $3'})
	MEM=$(free -h | awk '/^Mem:/ {print $3 "/" $2}')
	SWAP=$(free -h | awk '/^Swap:/ {print $3 "/" $2}')
	CPUTEMP=$(sensors | grep 'Package id 0:' | awk '{print substr($4,2)}')
	BATTERY=$(cat /sys/class/power_supply/BAT0/capacity)
	CPUFREQ=$(cpupower frequency-info | grep "asserted by call" | awk {'print $4'})'Ghz'
	BATTERYSTAT=$(cat /sys/class/power_supply/BAT0/status)
	UPTIME=$(uptime -p | awk '{$1=""; print $0}' )

	if [ $BATTERYSTAT = Charging ]
	then
	BATTERYSTATICON="▲"
	
	elif [ $BATTERYSTAT = Discharging ]
	then
	BATTERYSTATICON="▼"	
	
	elif [ $BATTERYSTAT = Full ]
	then
	BATTERYSTATICON="▇"
	fi

xsetroot -name "$UPTIME | $DISKUSED/$DISKTOTAL $DISKUSEDP | $MEM $SWAP | $CPUFREQ $CPUTEMP | $LOCALTIME  [ $BATTERY%$BATTERYSTATICON ]"
        sleep 8s
done & 
